version: 2
jobs:
    build:
        docker:
            - image: ubuntu:16.04
        environment:
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        steps:
            - run:
                name: install pre-dependencies
                command: |
                    apt update
                    apt install curl -y
            - run:
                name: install dependencies
                command: |
                    curl -sL https://deb.nodesource.com/setup_9.x | bash
                    apt install -y nodejs npm
                    npm install ganache-cli truffle

            - run:
                name: run ganache
                command: |
                  ganache-cli &

            - checkout

            - run:
                name: install dependencies
                command: |
                    truffle test
